export default recipes = [
    {
      name: "Spaghetti Carbonara",
      ingredients: ["spaghetti", "pancetta", "garlic", "eggs", "parmesan cheese"],
      instructions: [
        "Boil spaghetti according to package instructions.",
        "In a pan, cook pancetta until crispy.",
        "Add minced garlic to the pan and cook until fragrant.",
        "In a bowl, whisk together eggs and parmesan cheese.",
        "When spaghetti is cooked, drain and add to the pan with pancetta and garlic. Remove pan from heat.",
        "Add egg mixture to the spaghetti and toss quickly to prevent the eggs from scrambling.",
        "Serve hot with additional parmesan cheese if desired.",
      ],
      prepTime: 10,
      cookTime: 20,
      servings: 4,
    },
    {
      name: "Chicken Alfredo",
      ingredients: [
        "fettuccine",
        "chicken breast",
        "butter",
        "heavy cream",
        "garlic",
        "parmesan cheese",
      ],
      instructions: [
        "Boil fettuccine according to package instructions.",
        "Season chicken breasts with salt and pepper and cook in a pan until browned on both sides.",
        "Remove chicken from pan and add butter to the pan.",
        "Add minced garlic and cook until fragrant.",
        "Add heavy cream and grated parmesan cheese to the pan, and stir until cheese is melted.",
        "Add cooked fettuccine to the pan and toss to coat with the sauce.",
        "Slice chicken breasts and serve over the pasta.",
      ],
      prepTime: 15,
      cookTime: 25,
      servings: 6,
    },
    {
      name: "Vegetable Stir Fry",
      ingredients: [
        "rice",
        "carrots",
        "broccoli",
        "red bell pepper",
        "snow peas",
        "soy sauce",
        "sesame oil",
      ],
      instructions: [
        "Cook rice according to package instructions.",
        "Cut carrots and broccoli into small pieces, and thinly slice red bell pepper.",
        "Heat sesame oil in a wok or large pan over high heat.",
        "Add vegetables and stir fry for 5-7 minutes until tender.",
        "Add snow peas and soy sauce to the pan and stir to combine.",
        "Serve over cooked rice.",
      ],
      prepTime: 10,
      cookTime: 15,
      servings: 4,
    },
    {
      name: "Grilled Cheese Sandwich",
      ingredients: ["bread", "cheddar cheese", "butter"],
      instructions: [
        "Preheat a non-stick pan over medium heat.",
        "Butter one side of each slice of bread.",
        "Place one slice of bread, butter-side down, in the pan.",
        "Add a layer of cheddar cheese on top of the bread.",
        "Top with the other slice of bread, butter-side up.",
        "Cook until the bottom slice of bread is golden brown, then flip and cook until the other side is golden brown and the cheese is melted.",
        "Serve hot.",
      ],
      prepTime: 5,
      cookTime: 10,
      servings: 2,
    },
  ];